# Travis CI config for AppStream

dist: focal
language: c
sudo: required

services:
  - docker

compiler:
  - gcc
  #- clang -- Fails to compile GIR: clang: error: unknown argument: '-fdebug-prefix-map=..' (likely needs newer clang)

before_script:
  - docker build -t appstream -f tests/ci/Dockerfile .
  - if [ "$CC" = "clang" ]; then export CVENDOR="clang" CXX="clang" CC="clang"; fi
  - if [ "$CC" = "gcc" ]; then export CVENDOR="gcc" CXX="g++" CC="gcc"; fi

script:
  - docker run -t -e COMPILER_VENDOR=$CVENDOR -e CC=$CC -e CXX=$CXX -v `pwd`:/build appstream
    ./tests/ci/build_and_test.sh
